language: python
python:
- 2.7
install:
- echo $PYPI_USERNAME
- python setup.py develop
script:
- nosetests
services:
- elasticsearch
- mongodb
- rabbitmq
- redis-server
env:
  global:
  # PYPI_SERVER, PYPI_USERNAME, PYPI_PASSWORD
  - PYPI_SERVER=https://pypi.vandelay.io/balanced/prod/
  - PYPI_USERNAME=omnibus
