language: python
python:
- 2.7
install:
- echo $PYPI_USERNAME
- ./create-pypi.sh
- python setup.py develop
- pip install -e .[tests]
script:
- nosetests
env:
  global:
  # PYPI_SERVER, PYPI_USERNAME, PYPI_PASSWORD
  - PYPI_SERVER=https://pypi.vandelay.io/balanced/prod/
  - PYPI_USERNAME=omnibus
