language: python
python:
- 2.7
install:
- echo $PYPI_USERNAME
- echo -e "drepository: $PYPI_SERVER\n\tusername: $PYPI_USERNAME\n\tpassword: $PYPI_PASSWORD\n"
script:
- nosetests
env:
  global:
  # PYPI_SERVER, PYPI_USERNAME, PYPI_PASSWORD
  - PYPI_SERVER=https://pypi.vandelay.io/balanced/prod/
  - PYPI_USERNAME=omnibus
