language: python
python:
- 2.7
install:
- echo $PYPI_USERNAME
- echo -e "[distutils]\\n\tpypi\n\tbalanced\n\n[balanced]\n\trepository: $PYPI_SERVER\n\tusername: $PYPI_USERNAME\n\tpassword: $PYPI_PASSWORD\n" > ~/.pypirc
- python setup.py develop
script:
- find balanced_service -name \*.py \ | xargs $PYENV_HOME/bin/pep8 --ignore=E711 | tee pep8.out
after_success:
- coverage.py coverage.xml balanced_service.models:91 balanced_service.resources:92
services:
- elasticsearch
- mongodb
- rabbitmq
- redis-server
env:
  global:
  # PYPI_SERVER, PYPI_USERNAME, PYPI_PASSWORD
  - PYPI_SERVER=https://pypi.vandelay.io/balanced/prod/
  - PYPI_USERNAME=omnibus
