language: python
python:
- 2.7
install:
- echo $PYPI_USERNAME
- "./create-pypi.sh"
- pip install -U setuptools
- pip install https://pypi.python.org/packages/source/S/SQLAlchemy/SQLAlchemy-0.8.4.tar.gz#md5=fd517e1bb4031cac1e3fa00108111b38
- pip install https://pypi.python.org/packages/source/r/redis/redis-2.9.1.tar.gz#md5=1da8ff78be75d7acf5d4684e77fc3606
- python setup.py develop
- pip install -e .[tests]
script:
- nosetests
env:
  global:
  - PYPI_SERVER=https://pypi.vandelay.io/balanced/prod/
  - PYPI_USERNAME=omnibus
  - secure: JHUAulJafCnZ51yJ/dFltdN07aneSLImjDHi9xjAITkR+XL0f9F+h990+O03elEuYxlhqFqiCjEOoyd+L+CaMu2uWjfEUNENabSUZ65aRJL/W9XA9677XvwbCHB+pLEfWe5UWGtB+OxKNnl3O8vJ4zq6jGp3xUpTVnVcHqPpzdM=
