language: python
python:
- 2.7
install:
- echo $PYPI_USERNAME
- "./create-pypi.sh"
- pip install -e .[tests]
- python setup.py develop
script:
- nosetests
env:
  global:
  - PYPI_SERVER=https://pypi.vandelay.io/balanced/prod/
  - PYPI_USERNAME=omnibus
  - secure: JHUAulJafCnZ51yJ/dFltdN07aneSLImjDHi9xjAITkR+XL0f9F+h990+O03elEuYxlhqFqiCjEOoyd+L+CaMu2uWjfEUNENabSUZ65aRJL/W9XA9677XvwbCHB+pLEfWe5UWGtB+OxKNnl3O8vJ4zq6jGp3xUpTVnVcHqPpzdM=
